# Generated by Django 2.1.3 on 2018-11-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cover_pic',
            new_name='coverpic',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profilepic',
        ),
        migrations.AlterField(
            model_name='category',
            name='catImg',
            field=models.FileField(upload_to='catImg/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='cityImg',
            field=models.ImageField(height_field='heightField', upload_to='cityImg/', width_field='widthField'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subCatImg',
            field=models.FileField(upload_to='subCatImg/'),
        ),
    ]
