# Generated by Django 2.1.3 on 2018-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folks', '0002_auto_20181108_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='coverpic',
            field=models.ImageField(height_field='heightField', upload_to='coverpic/', width_field='widthField'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(height_field='heightField', upload_to='profilepic/', width_field='widthField'),
        ),
    ]
