# Generated by Django 2.1.3 on 2018-11-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folks', '0003_auto_20181108_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
